import = ["~/.config/alacritty/themes/themes/solarized_osaka.toml"]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "TMUX"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
title = "BearyDev"
# dimensions.columns = 170
# dimensions.lines = 50
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "both"
startup_mode = "Maximized"

[font]
normal.family = "ComicShannsMono Nerd Font"
normal.style = "Regular"
size = 18

[cursor]
style.shape = "Block"
style.blinking = "Always"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[keyboard]
bindings = [{ key = "T", mods = "Command", action = "none" }]
