"""Turn a list of Endpoint objects into Postman Collection v2.1 JSON."""

from __future__ import annotations

import json
from collections import OrderedDict
from typing import Any

from common import Endpoint


SCHEMA_URL = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"


def build_collection(
    endpoints: list[Endpoint],
    name: str,
    include_scripts: bool = False,
) -> dict[str, Any]:
    folders: "OrderedDict[str, list[dict[str, Any]]]" = OrderedDict()
    for ep in endpoints:
        folders.setdefault(ep.folder or "Default", []).append(
            _request_item(ep, include_scripts)
        )

    items = [{"name": folder, "item": requests} for folder, requests in folders.items()]

    collection: dict[str, Any] = {
        "info": {
            "name": name,
            "schema": SCHEMA_URL,
            "description": "Auto-generated by postman-collection-generator skill.",
        },
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{token}}", "type": "string"}],
        },
        "item": items,
        "variable": [
            {"key": "baseUrl", "value": "{{baseUrl}}", "type": "string"},
        ],
    }
    return collection


def build_environment(name: str, base_url: str) -> dict[str, Any]:
    return {
        "name": f"{name} local",
        "values": [
            {"key": "baseUrl", "value": base_url, "enabled": True, "type": "default"},
            {"key": "token", "value": "", "enabled": True, "type": "secret"},
            {"key": "apiKey", "value": "", "enabled": True, "type": "secret"},
        ],
        "_postman_variable_scope": "environment",
    }


# ---------- internal ----------


def _request_item(ep: Endpoint, include_scripts: bool) -> dict[str, Any]:
    url = _build_url(ep)
    headers: list[dict[str, str]] = []
    body_block: dict[str, Any] | None = None
    if ep.body is not None and ep.method not in {"GET", "DELETE", "HEAD", "OPTIONS"}:
        headers.append({"key": "Content-Type", "value": "application/json"})
        body_block = {
            "mode": "raw",
            "raw": json.dumps(ep.body, indent=2, ensure_ascii=False),
            "options": {"raw": {"language": "json"}},
        }

    request: dict[str, Any] = {
        "method": ep.method,
        "header": headers,
        "url": url,
    }
    if body_block is not None:
        request["body"] = body_block

    auth_block = _auth_block(ep.auth)
    if auth_block is not None:
        request["auth"] = auth_block

    if ep.description:
        request["description"] = ep.description

    item: dict[str, Any] = {
        "name": ep.name or f"{ep.method} {ep.path}",
        "request": request,
        "response": [],
    }

    if include_scripts:
        item["event"] = [
            {
                "listen": "test",
                "script": {
                    "type": "text/javascript",
                    "exec": [
                        "pm.test('Status is 2xx', function () {",
                        "    pm.expect(pm.response.code).to.be.within(200, 299);",
                        "});",
                    ],
                },
            }
        ]

    return item


def _build_url(ep: Endpoint) -> dict[str, Any]:
    # Path: split and preserve :params.
    segments = [s for s in ep.path.split("/") if s]
    query = [
        {
            "key": q["key"],
            "value": "",
            "disabled": True,
            "description": q.get("description", ""),
        }
        for q in ep.query_params
    ]
    variables = [
        {"key": v["key"], "value": "", "description": v.get("description", "")}
        for v in ep.path_params
    ]
    raw = "{{baseUrl}}/" + "/".join(segments) if segments else "{{baseUrl}}/"
    if query:
        raw += "?" + "&".join(f"{q['key']}=" for q in ep.query_params)
    url: dict[str, Any] = {
        "raw": raw,
        "host": ["{{baseUrl}}"],
        "path": segments,
    }
    if query:
        url["query"] = query
    if variables:
        url["variable"] = variables
    return url


def _auth_block(auth: str | None) -> dict[str, Any] | None:
    if auth is None:
        return None  # inherit collection-level bearer
    if auth == "bearer":
        # Explicit bearer = same as collection default, no need to override.
        return None
    if auth == "apikey":
        return {
            "type": "apikey",
            "apikey": [
                {"key": "key", "value": "x-api-key", "type": "string"},
                {"key": "value", "value": "{{apiKey}}", "type": "string"},
                {"key": "in", "value": "header", "type": "string"},
            ],
        }
    if auth == "none":
        return {"type": "noauth"}
    return None
