-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- ╭─────────────────────────────────────────────────────────╮
-- │ Todo Comment Demo                                       │
-- ╰─────────────────────────────────────────────────────────╯
-- NOTE:
-- PERF:
-- HACK:
-- TODO:
-- WARN:
-- FIX:
-- BUG:
-- FIXIT:
-- ISSUE:
-- WARNING:
-- TEST:
