return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts_extend = { "ensure_installed" },
  opts = {
    ensure_installed = {
      "flake8",
      "pyright",
      "bash-debug-adapter",
      "ast-grep",
      "autopep8",
      "beautysh",
      "biome",
      "chrome-debug-adapter",
      "clang-format",
      "clangd",
      "codelldb",
      "cortex-debug",
      "cpplint",
      "cpptools",
      "csharp-language-server",
      "csharpier",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "debugpy",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-language-server",
      "emmet-ls",
      "erb-lint",
      "eslint-lsp",
      "eslint_d",
      "firefox-debug-adapter",
      "fixjson",
      "glow",
      "go-debug-adapter",
      "graphql-language-service-cli",
      "hadolint",
      "html-lsp",
      "htmlbeautifier",
      "htmlhint",
      "jq",
      "js-debug-adapter",
      "json-lsp",
      "jsonlint",
      "lua-language-server",
      "luacheck",
      -- "markmap-cli",
      -- "harper-ls", -- not use because it have always spell checker
      "marksman",
      "markuplint",
      "netcoredbg",
      "nginx-language-server",
      "nxls",
      "omnisharp",
      "omnisharp-mono",
      "prettier",
      "prettierd",
      "prisma-language-server",
      "prosemd-lsp",
      "pylint",
      "python-lsp-server",
      "ruff-lsp",
      "rust-analyzer",
      "rustywind",
      "selene",
      "shellcheck",
      "shfmt",
      "snyk",
      "some-sass-language-server",
      "sql-formatter",
      "sqlfluff",
      "sqlfmt",
      "sqlls",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "trivy",
      "ts-standard",
      "typescript-language-server",
      "vim-language-server",
      "vtsls",
      "write-good",
      "yaml-language-server",
      "yamlfix",
      "yamlfmt",
      "yamllint",
      "circleci-yaml-language-server",
      "sonarlint-language-server",
      "cfn-lint",
      "gitlab-ci-ls",
      -- "hydra-lsp",
      -- "spectral-language-server",
      "zk",
      "markdown-oxide",
      -- "jdtls",
      "gopls",
      "bash-language-server",
      "java-debug-adapter",
      "dot-language-server",
      "htmx-lsp",
      "mdx-analyzer",
      "vint",
      "asm-lsp",
      -- "arduino-language-server",
      "zls",
      "svelte-language-server",
      "gradle-language-server",
      "vetur-vls",
      "vue-language-server", -- volar
      "luau-lsp",
      -- "deno",
      -- "oxlint",
      "goimports",
      "gofumpt",
      "gomodifytags",
      "impl",
      "delve",
      "semgrep",
      "jdtls",
      "vscode-java-decompiler",
      "google-java-format",
      "stylelint",
      "termux-language-server",
      "shellharden",
      "gersemi",
      "cmakelint",
      "cmakelang",
      "neocmakelsp",
      "cmake-language-server",
      "sleek", -- sql
      "eugene", -- sql
      "dart-debug-adapter",
      "dcm",
      "kulala-fmt", -- http
    },
    ui = {
      icons = {
        package_installed = "",
        package_pending = "",
        package_uninstalled = "",
      },
    },
  },
  ---@param opts MasonSettings | {ensure_installed: string[]}
  config = function(_, opts)
    require("mason").setup(opts)
    local mr = require("mason-registry")
    mr:on("package:install:success", function()
      vim.defer_fn(function()
        -- trigger FileType event to possibly load this newly installed LSP server
        require("lazy.core.handler.event").trigger({
          event = "FileType",
          buf = vim.api.nvim_get_current_buf(),
        })
      end, 100)
    end)

    mr.refresh(function()
      for _, tool in ipairs(opts.ensure_installed) do
        local p = mr.get_package(tool)
        if not p:is_installed() then
          p:install()
        end
      end
    end)
  end,
}
